// SearchPanel — minimal vanilla implementation
//
// Source of truth for behavior is design-spec/search-panel/specs/search-panel/spec.md.
// Source of truth for fetch + error semantics is design-spec/search-panel/data-fetching.md.
// Source of truth for component structure is design-spec/search-panel/contracts/ui-schema.yaml.
//
// Trace anchors below match those generated by design-to-spec, so a reader can
// jump from spec.md to the implementation by searching for `state:<id>`,
// `binding:<index>:<direction>`, or `request:<id>`.

import { mockSearch, getMockMode, setMockMode } from './mock-search.js';

// ---------------------------------------------------------------------------
// 1. Render the panel skeleton (component:searchPanel)
// ---------------------------------------------------------------------------

const root = document.querySelector('#search-panel');
root.innerHTML = `
  <div class="search-panel__input-row">
    <input
      class="search-panel__input"
      type="text"
      placeholder="搜索关键词"
      data-trace="component:searchInput"
    />
    <button
      class="search-panel__submit"
      data-trace="component:submitBtn"
      disabled
    >搜</button>
  </div>
  <div
    class="search-panel__validation-hint"
    data-trace="component:validationHint"
  ></div>
  <hr class="search-panel__divider" />
  <div class="results-region" data-trace="component:resultsRegion"></div>
`;

const inputEl = root.querySelector('.search-panel__input');
const submitEl = root.querySelector('.search-panel__submit');
const validationEl = root.querySelector('.search-panel__validation-hint');
const resultsEl = root.querySelector('.results-region');

// Mock-mode dropdown wiring (test scaffolding, not part of the component contract)
const mockModeEl = document.querySelector('#mock-mode');
mockModeEl.value = getMockMode();
mockModeEl.addEventListener('change', (e) => setMockMode(e.target.value));

// ---------------------------------------------------------------------------
// 2. State machine (state:idle / loading / success / empty / error / invalidKeyword)
// ---------------------------------------------------------------------------

let currentState = 'idle';
let lastSubmittedKeyword = '';
let lastErrorCode = '';
let inFlightController = null;
let rateLimitedRetryTimer = null;
let rateLimitedAttempts = 0;

function setState(next) {
  currentState = next;
  root.dataset.state = next;
  render();
}

// ---------------------------------------------------------------------------
// 3. Bindings
// ---------------------------------------------------------------------------

// binding:1:ui_to_api — searchInput.value -> keyword (with trim + length validation)
inputEl.addEventListener('input', () => {
  const keyword = inputEl.value.trim();
  // state:disabled (element-scoped local state) — submitBtn greyed out when keyword empty
  submitEl.disabled = keyword.length === 0;
  // Clear validation hint as soon as user edits
  if (root.dataset.validationError === 'true') {
    root.dataset.validationError = 'false';
    validationEl.textContent = '';
  }
});

inputEl.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && !submitEl.disabled) {
    submit();
  }
});

submitEl.addEventListener('click', () => submit());

// binding:7:ui_to_event — tap-search-submit
function emitTrackingEvent(name, payload) {
  // In production this would call the team's tracking SDK.
  // Sample uses console.log so readers can see when each event fires.
  console.log(`[tracking] ${name}`, payload);
}

// ---------------------------------------------------------------------------
// 4. Request lifecycle (request:searchRequest)
// ---------------------------------------------------------------------------

async function submit() {
  const keyword = inputEl.value.trim();
  if (keyword.length === 0) return;

  // ui_to_event tap-search-submit
  emitTrackingEvent('tap-search-submit', {
    keyword,
    keyword_length: keyword.length,
  });

  // concurrency_policy: abortable. Cancel any prior in-flight request.
  if (inFlightController) {
    inFlightController.abort();
    inFlightController = null;
  }
  if (rateLimitedRetryTimer !== null) {
    clearTimeout(rateLimitedRetryTimer);
    rateLimitedRetryTimer = null;
  }

  lastSubmittedKeyword = keyword;
  setState('loading');

  await runSearch(keyword);
}

async function runSearch(keyword, isAutoRetry = false) {
  const controller = new AbortController();
  inFlightController = controller;

  let response;
  try {
    response = await mockSearch({ keyword, page: 1, signal: controller.signal });
  } catch (err) {
    if (err.name === 'AbortError') {
      // concurrency_policy.stale_response: ignore — drop this response entirely
      return;
    }
    // Anything else is treated as a network failure
    transitionToError(keyword, 'NETWORK_ERROR', '网络异常，请重试');
    return;
  }

  // If a newer request started after this one, drop the response (stale)
  if (controller !== inFlightController) return;
  inFlightController = null;

  // state_machine: loading -> success / empty / error / invalidKeyword
  if (response.code === 0) {
    window.__lastSearchResponse = response; // for the renderer
    if (response.data.results.length > 0) {
      setState('success');
      // ui_to_event view-search-result
      emitTrackingEvent('view-search-result', {
        keyword,
        result_count: response.data.total,
      });
    } else {
      setState('empty');
      emitTrackingEvent('view-search-empty', { keyword });
    }
    return;
  }

  // Business error path
  lastErrorCode = response.code;

  if (response.code === 'INVALID_KEYWORD') {
    // state:invalidKeyword — element-scoped, NOT a full error state
    root.dataset.validationError = 'true';
    validationEl.textContent = response.message;
    setState('invalidKeyword');
    return;
  }

  if (response.code === 'FORBIDDEN') {
    // state_machine: loading -> idle (navigates to /login)
    console.log('[nav] would redirect to /login (sample stub)');
    setState('idle');
    return;
  }

  if (response.code === 'RATE_LIMITED' && !isAutoRetry && rateLimitedAttempts < 1) {
    // retry_policy: auto_on_rate_limited, max_attempts: 1, fixed 5s backoff
    rateLimitedAttempts += 1;
    showToast('请求过于频繁，请稍后再试（5 秒后自动重试）');
    rateLimitedRetryTimer = setTimeout(() => {
      rateLimitedRetryTimer = null;
      hideToast();
      runSearch(keyword, true);
    }, 5000);
    // Stay in loading while waiting for auto-retry
    return;
  }

  // NETWORK_ERROR / RATE_LIMITED (after retry exhausted) / INTERNAL_ERROR
  rateLimitedAttempts = 0;
  const message = errorMessage(response.code, response.message);
  transitionToError(keyword, response.code, message);
}

function transitionToError(keyword, code, message) {
  lastErrorCode = code;
  window.__lastErrorMessage = message;
  setState('error');
  emitTrackingEvent('view-search-error', { keyword, error_code: code });
}

function errorMessage(code, fallback) {
  switch (code) {
    case 'NETWORK_ERROR':
      return '网络异常，请重试';
    case 'RATE_LIMITED':
      return '请求过于频繁，请稍后再试';
    case 'INTERNAL_ERROR':
      return '服务异常，请联系管理员';
    default:
      return fallback || '请求失败';
  }
}

// ---------------------------------------------------------------------------
// 5. Renderers (one per state)
// ---------------------------------------------------------------------------

function render() {
  // Common: submit button loading flag
  submitEl.dataset.loading = currentState === 'loading' ? 'true' : 'false';

  switch (currentState) {
    case 'idle':
      resultsEl.innerHTML = `
        <div class="results-region__guide" data-trace="state:idle">
          <span>请输入关键词后</span>
          <span>点击搜索</span>
        </div>
      `;
      return;

    case 'loading':
      resultsEl.innerHTML = `
        <ul class="skeleton-list" data-trace="state:loading">
          ${Array.from({ length: 3 })
            .map(
              () => `
                <li class="skeleton-row" data-trace="component:skeletonRow">
                  <div class="skeleton-row__title"></div>
                  <div class="skeleton-row__summary"></div>
                </li>
              `,
            )
            .join('')}
        </ul>
      `;
      return;

    case 'success': {
      const data = window.__lastSearchResponse.data;
      // binding:3:api_to_ui (data.total -> resultCount)
      // binding:4:api_to_ui (data.results -> resultList)
      resultsEl.innerHTML = `
        <p class="results-region__count" data-trace="component:resultCount">
          共 ${data.total} 条结果
        </p>
        <ul class="result-list" data-trace="component:resultList state:success">
          ${data.results.map((item) => renderResultItem(item)).join('')}
        </ul>
      `;
      return;
    }

    case 'empty':
      resultsEl.innerHTML = `
        <div class="results-region__empty" data-trace="state:empty">
          <span class="icon" data-trace="component:emptyIcon"></span>
          <span data-trace="component:emptyText">未找到相关结果</span>
        </div>
      `;
      return;

    case 'error':
      resultsEl.innerHTML = `
        <div class="results-region__error" data-trace="state:error">
          <span class="icon" data-trace="component:errorIcon">!</span>
          <span class="text" data-trace="component:errorText">${
            window.__lastErrorMessage || '请求失败'
          }</span>
          <button
            class="retry-button"
            data-trace="component:retryButton binding:8:ui_to_event"
          >重试</button>
        </div>
      `;
      // state_machine: error -> loading on retryButton.onClick
      resultsEl.querySelector('.retry-button').addEventListener('click', () => {
        emitTrackingEvent('tap-search-retry', {
          keyword: lastSubmittedKeyword,
          error_code: lastErrorCode,
        });
        rateLimitedAttempts = 0;
        setState('loading');
        runSearch(lastSubmittedKeyword);
      });
      return;

    case 'invalidKeyword':
      // resultsRegion stays in idle layout per spec; validation hint is
      // toggled separately by the input handler.
      resultsEl.innerHTML = `
        <div class="results-region__guide" data-trace="state:invalidKeyword">
          <span>请修正输入后</span>
          <span>重新搜索</span>
        </div>
      `;
      return;
  }
}

// binding:5:api_to_ui (results[].title) + binding:6:api_to_ui (results[].summary, hide if null)
function renderResultItem(item) {
  const summaryHtml = item.summary
    ? `<p class="result-item__summary">${escapeHtml(item.summary)}</p>`
    : `<p class="result-item__summary" data-empty="true"></p>`;
  return `
    <li class="result-item" data-trace="component:resultItem">
      <p class="result-item__title">${escapeHtml(item.title)}</p>
      ${summaryHtml}
    </li>
  `;
}

function escapeHtml(s) {
  return String(s).replace(
    /[&<>"']/g,
    (c) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#39;',
      })[c],
  );
}

// ---------------------------------------------------------------------------
// 6. Toast (rate-limit feedback)
// ---------------------------------------------------------------------------

let toastEl = null;

function showToast(text) {
  hideToast();
  toastEl = document.createElement('div');
  toastEl.className = 'toast';
  toastEl.textContent = text;
  document.body.appendChild(toastEl);
}

function hideToast() {
  if (toastEl) {
    toastEl.remove();
    toastEl = null;
  }
}

// ---------------------------------------------------------------------------
// 7. Initial render
// ---------------------------------------------------------------------------

setState('idle');
